-- Partner referral commission system, SAR-only.
-- Partner earns % of Wasil revenue generated by referred merchants.

-- Add SAR amount to commissions
ALTER TABLE commissions
  ADD COLUMN IF NOT EXISTS amount_sar numeric;

-- Migrate existing rows if any
UPDATE commissions SET amount_sar = COALESCE(amount_usd, 0) WHERE amount_sar IS NULL;

ALTER TABLE commissions
  ALTER COLUMN amount_sar SET NOT NULL;

-- Make sure every merchant profile can have a referral code
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS is_partner boolean NOT NULL DEFAULT false;

-- Helper: create partner commission from a new merchant payout
CREATE OR REPLACE FUNCTION public.create_partner_commission(payout_uuid uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p payouts%ROWTYPE;
  store_owner uuid;
  ref_record referrals%ROWTYPE;
  partner_pct numeric;
  revenue_share numeric;
BEGIN
  SELECT * INTO p FROM payouts WHERE id = payout_uuid;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT owner_id INTO store_owner FROM stores WHERE id = p.store_id;
  IF store_owner IS NULL THEN RETURN; END IF;

  SELECT * INTO ref_record
  FROM referrals
  WHERE referred_merchant_id = store_owner
  LIMIT 1;

  IF ref_record.id IS NULL THEN RETURN; END IF;

  SELECT partner_commission_percent INTO partner_pct FROM platform_config WHERE id = 1;
  partner_pct := COALESCE(partner_pct, 10);

  -- Partner earns % of Wasil revenue from this payout = commission + plan fee deduction
  revenue_share := p.commission_sar + p.plan_fee_deduction_sar;
  IF revenue_share <= 0 THEN RETURN; END IF;

  INSERT INTO commissions (referral_id, amount_sar, source_type, status)
  VALUES (ref_record.id, ROUND((revenue_share * partner_pct / 100) * 100) / 100, 'order_commission', 'pending');
END;
$$;

-- Also create commission when a subscription charge is paid (plan fee revenue)
CREATE OR REPLACE FUNCTION public.create_partner_commission_from_subscription(charge_uuid uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  sc subscription_charges%ROWTYPE;
  store_owner uuid;
  ref_record referrals%ROWTYPE;
  partner_pct numeric;
BEGIN
  SELECT * INTO sc FROM subscription_charges WHERE id = charge_uuid;
  IF NOT FOUND OR sc.status != 'paid' THEN RETURN; END IF;

  SELECT owner_id INTO store_owner FROM stores WHERE id = sc.store_id;
  IF store_owner IS NULL THEN RETURN; END IF;

  SELECT * INTO ref_record
  FROM referrals
  WHERE referred_merchant_id = store_owner
  LIMIT 1;

  IF ref_record.id IS NULL THEN RETURN; END IF;

  SELECT partner_commission_percent INTO partner_pct FROM platform_config WHERE id = 1;
  partner_pct := COALESCE(partner_pct, 10);

  INSERT INTO commissions (referral_id, amount_sar, source_type, status)
  VALUES (ref_record.id, ROUND((sc.amount_sar * partner_pct / 100) * 100) / 100, 'subscription_fee', 'pending');
END;
$$;

-- Trigger on payouts: create partner commission
CREATE OR REPLACE FUNCTION public.on_payout_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.create_partner_commission(NEW.id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payout_partner_commission ON payouts;
CREATE TRIGGER payout_partner_commission
  AFTER INSERT ON payouts
  FOR EACH ROW
  EXECUTE FUNCTION public.on_payout_created();

-- Trigger on subscription_charges: create partner commission when paid
CREATE OR REPLACE FUNCTION public.on_subscription_charge_paid()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'paid' AND OLD.status IS DISTINCT FROM 'paid' THEN
    PERFORM public.create_partner_commission_from_subscription(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS subscription_charge_partner_commission ON subscription_charges;
CREATE TRIGGER subscription_charge_partner_commission
  BEFORE UPDATE OF status ON subscription_charges
  FOR EACH ROW
  EXECUTE FUNCTION public.on_subscription_charge_paid();

-- RLS for partner data
DROP POLICY IF EXISTS "Referrers can view their referrals" ON referrals;
CREATE POLICY "Referrers can view their referrals"
  ON referrals FOR SELECT TO authenticated
  USING (auth.uid() = referrer_id);

DROP POLICY IF EXISTS "Referrers can view their commissions" ON commissions;
CREATE POLICY "Referrers can view their commissions"
  ON commissions FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM referrals WHERE referrals.id = commissions.referral_id AND referrals.referrer_id = auth.uid()));

DROP POLICY IF EXISTS "Admins can manage referrals" ON referrals;
CREATE POLICY "Admins can manage referrals"
  ON referrals FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can manage commissions" ON commissions;
CREATE POLICY "Admins can manage commissions"
  ON commissions FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());
